spring:
  application:
    name: commerce-server
  profiles:
    active: secret
  datasource: ##?????? ??
    url: jdbc:mysql://localhost:3307/commerce_server_local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ON_SECRET
    password: ON_SECRET
  jpa: ##??????? ??? ? ??? ????
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        highlight_sql: true
        use_sql_comments: true